-- V1: Create tables
CREATE TABLE mt_usuario_java (
    id_usuario NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
    nome_usuario VARCHAR2(255 CHAR) NOT NULL,
    cpf_usuario VARCHAR2(255 CHAR) NOT NULL,
    email_usuario VARCHAR2(255 CHAR) NOT NULL,
    senha_usuario VARCHAR2(255 CHAR) NOT NULL,
    cnh_usuario VARCHAR2(255 CHAR) NOT NULL,
    data_nascimento_usuario TIMESTAMP(6),
    criado_em_usuario TIMESTAMP(6),
    token_usuario VARCHAR2(255 CHAR),
    PRIMARY KEY (id_usuario)
);

CREATE TABLE mt_permissao_java (
    id_permissao NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
    nome_permissao VARCHAR2(100 CHAR) NOT NULL,
    descricao VARCHAR2(255 CHAR),
    PRIMARY KEY (id_permissao)
);

CREATE TABLE mt_usuario_permissao_java (
    usuario_id NUMBER(19,0) NOT NULL,
    permissao_id NUMBER(19,0) NOT NULL,
    papel VARCHAR2(255 CHAR),
    PRIMARY KEY (usuario_id, permissao_id),
    FOREIGN KEY (usuario_id) REFERENCES mt_usuario_java(id_usuario),
    FOREIGN KEY (permissao_id) REFERENCES mt_permissao_java(id_permissao)
);

CREATE TABLE mt_telefone_java (
    id_telefone NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
    numero VARCHAR2(255 CHAR) NOT NULL,
    tipo VARCHAR2(255 CHAR),
    usuario_id NUMBER(19,0),
    PRIMARY KEY (id_telefone),
    FOREIGN KEY (usuario_id) REFERENCES mt_usuario_java(id_usuario)
);

CREATE TABLE mt_patio_java (
    id_patio NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
    nome_patio VARCHAR2(255 CHAR) NOT NULL,
    motos_totais_patio NUMBER(10,0) NOT NULL,
    motos_disponiveis_patio NUMBER(10,0) NOT NULL,
    data_patio TIMESTAMP(6),
    PRIMARY KEY (id_patio)
);

CREATE TABLE mt_moto_java (
    id_moto NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
    placa_moto VARCHAR2(255 CHAR) NOT NULL,
    modelo_moto VARCHAR2(255 CHAR) NOT NULL,
    ano_moto NUMBER(10,0) NOT NULL,
    quilometragem_moto NUMBER(10,0) NOT NULL,
    identificador_moto VARCHAR2(255 CHAR),
    estado_moto NUMBER(3,0) CHECK (estado_moto BETWEEN 0 AND 3),
    condicoes_moto VARCHAR2(255 CHAR),
    moto_patio_atual_id NUMBER(19,0),
    moto_patio_origem_id NUMBER(19,0),
    contrato_moto_id NUMBER(19,0) UNIQUE,
    PRIMARY KEY (id_moto),
    FOREIGN KEY (moto_patio_atual_id) REFERENCES mt_patio_java(id_patio),
    FOREIGN KEY (moto_patio_origem_id) REFERENCES mt_patio_java(id_patio)
);

CREATE TABLE mt_contrato_java (
    id_contrato NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
    clausulas_contrato VARCHAR2(255 CHAR),
    data_de_entrada_contrato TIMESTAMP(6) NOT NULL,
    horario_de_devolucao_contrato TIMESTAMP(6) NOT NULL,
    data_de_expiracao_contrato TIMESTAMP(6) NOT NULL,
    data_ultima_renovacao_contrato TIMESTAMP(6),
    numero_renovacoes_contrato NUMBER(10,0) NOT NULL,
    renovacao_automatica_contrato NUMBER(1),
    valor_toral_contrato NUMBER(38,2) NOT NULL,
    quantidade_parcelas NUMBER(10,0) NOT NULL,
    ativo_contrato NUMBER(1),
    usuario_contrato_id NUMBER(19,0),
    moto_contrato_id NUMBER(19,0),
    PRIMARY KEY (id_contrato),
    FOREIGN KEY (usuario_contrato_id) REFERENCES mt_usuario_java(id_usuario),
    FOREIGN KEY (moto_contrato_id) REFERENCES mt_moto_java(id_moto)
);

CREATE TABLE mt_endereco_java (
    id_endereco NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
    logradouro VARCHAR2(150 CHAR) NOT NULL,
    numero VARCHAR2(20 CHAR) NOT NULL,
    complemento VARCHAR2(100 CHAR),
    bairro VARCHAR2(100 CHAR) NOT NULL,
    cidade VARCHAR2(100 CHAR) NOT NULL,
    estado VARCHAR2(2 CHAR) NOT NULL,
    cep VARCHAR2(10 CHAR) NOT NULL,
    referencia VARCHAR2(100 CHAR),
    patio_endereco_id NUMBER(19,0) UNIQUE,
    PRIMARY KEY (id_endereco),
    FOREIGN KEY (patio_endereco_id) REFERENCES mt_patio_java(id_patio)
);

CREATE TABLE mt_layout_patio_java (
    id_layout_patio NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
    descricao VARCHAR2(255 CHAR),
    comprimento NUMBER(38,2) NOT NULL,
    largura NUMBER(38,2) NOT NULL,
    altura NUMBER(38,2),
    data_criacao TIMESTAMP(6),
    patio_layout_patio_id NUMBER(19,0) UNIQUE,
    PRIMARY KEY (id_layout_patio),
    FOREIGN KEY (patio_layout_patio_id) REFERENCES mt_patio_java(id_patio)
);

CREATE TABLE mt_camera_java (
    id_camera NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
    nome_camera VARCHAR2(255 CHAR) NOT NULL,
    ip_camera VARCHAR2(255 CHAR),
    posx FLOAT(24),
    posy FLOAT(24),
    status NUMBER(3,0) NOT NULL CHECK (status BETWEEN 0 AND 3),
    patio_id NUMBER(19,0),
    PRIMARY KEY (id_camera),
    FOREIGN KEY (patio_id) REFERENCES mt_patio_java(id_patio)
);

CREATE TABLE mt_qrcode_ponto_java (
    id_qr_code_ponto NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
    identificador_qr_code VARCHAR2(255 CHAR) NOT NULL,
    posx FLOAT(24) NOT NULL,
    posy FLOAT(24) NOT NULL,
    layout_patio_id NUMBER(19,0),
    PRIMARY KEY (id_qr_code_ponto),
    FOREIGN KEY (layout_patio_id) REFERENCES mt_layout_patio_java(id_layout_patio)
);

